field_separator: "\t"
gpu_id: 0
reproducibility: True
model: HCTS
seed: 2023
curve1: 1.0
curve2: 1.0
margin: 0.1
scale: 0.1

embedding_size: 64
learning_rate: 0.0001
n_layers: 3
#num_neg_samples: 3
#cts
#cts_lamda: 0.01
#temp: 0.1
#ireg_lambda: 0.1
#ireg: True

stopping_step: 30
learner: 'adam'

u_u_cts: True
u_i_cts: True
i_u_cts: True
i_i_cts: True
s_t_transfer: True
t_s_transfer: True




source_domain:
  dataset: Amazon_book
  USER_ID_FIELD: user_id
  ITEM_ID_FIELD: item_id
  RATING_FIELD: rating
  NEG_PREFIX: neg_
  LABEL_FIELD: label
  load_col:
    inter: [user_id, item_id, rating]
  user_inter_num_interval: "[5,inf)"
  item_inter_num_interval: "[5,inf)"
  val_interval:
    rating: "[3,inf)"
  drop_filter_field: True
  train_neg_sample_args:
    strategy: 'by'
    by: 3
    distribution: 'uniform'
    dynamic': 'none'


target_domain:
  dataset: Amazon_movie
  USER_ID_FIELD: user_id
  ITEM_ID_FIELD: item_id
  RATING_FIELD: rating
  NEG_PREFIX: neg_
  LABEL_FIELD: label
  load_col:
    inter: [user_id, item_id, rating]
  user_inter_num_interval: "[5,inf)"
  item_inter_num_interval: "[5,inf)"
  val_interval:
    rating: "[3,inf)"
  drop_filter_field: True
  train_neg_sample_args:
    strategy: 'by'
    by: 3
    distribution: 'uniform'
    dynamic': 'none'
conv: skip
epoch_num: 100
train_batch_size: 4096
eval_batch_size: 4096
valid_metric: HIT@10
num_neg: 1

eval_args:
  split: {'RS': [0.8,0.1,0.1]}
  group_by: user
  order: RO
  mode: full

train_neg_sample_args:
